### PR TITLE
Fix terraform docs

### PR DESCRIPTION
**Pull request by osterman**
## what
* deprecate old shell script for supporting HCL2
* upgrade packages to support latest `terraform-docs`

## why
* script doesn't very well support all the terraform variable types
* no reason to keep it around now that `terraform-docs` natively supports HCL2

### CODE REVIEW

**Review by nitrocode — APPROVED** [review]
lgtm

**Review by aknysh — APPROVED** [review]

**Comment by 3h4x** [comment]
@osterman What about file `terraform-docs.awk`? Is it still used? No reference to it in `buildharness`

**Comment by osterman** [comment]
@3h4x This was also deprecated by #218 and should have all references removed.

**Comment by 3h4x** [comment]
> @3h4x This was also deprecated by #218 and should have all references removed.

I will remove it in https://github.com/cloudposse/build-harness/pull/230

**Pull request merged**
